[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "ParlAR"
version = "1.0.1"
description = "Dictado local a nivel sistema para Linux"
readme = "README.md"
requires-python = ">=3.12"
license = {file = "LICENSE"}
authors = [{name = "SGGaray"}]
dependencies = [
  "faster-whisper>=1.0.0",
  "sounddevice>=0.4.6",
  "numpy>=1.24",
  "pynput>=1.7.6",
]

[project.optional-dependencies]
vad = ["webrtcvad-wheels==2.0.14"]
cuda = [
    "nvidia-cublas-cu12==12.9.2.10",
    "nvidia-cuda-nvrtc-cu12==12.9.86",
    "nvidia-cudnn-cu12==9.24.0.43",
]

[project.scripts]
parlar = "parlar.__main__:main"
parlarctl = "parlar.control:parlarctl_main"

[project.urls]
Repository = "https://github.com/SGGaray/ParlAR"

[tool.setuptools.packages.find]
include = ["parlar*"]
