#!/usr/bin/env bash
# Desinstala artefactos generados por install.sh; conserva config y datos.
set -euo pipefail

DATA_BASE="${XDG_DATA_HOME:-$HOME/.local/share}"
CONFIG_BASE="${XDG_CONFIG_HOME:-$HOME/.config}"
INSTALL_HOME="${PARLAR_INSTALL_HOME:-$DATA_BASE/parlar}"
BIN_DIR="${PARLAR_BIN_DIR:-$HOME/.local/bin}"
VENV_DIR="$INSTALL_HOME/venv"
DESKTOP_PATH="$DATA_BASE/applications/parlar.desktop"
UNIT_PATH="$CONFIG_BASE/systemd/user/parlar.service"

if [[ "$INSTALL_HOME" != /* \
        || "$(basename -- "$INSTALL_HOME")" != "parlar" \
        || "$(dirname -- "$INSTALL_HOME")" == "/" ]]; then
    echo "!! ruta de instalación insegura: $INSTALL_HOME" >&2
    exit 1
fi
case "$INSTALL_HOME" in
    /|"$HOME"|"$HOME"/)
        echo "!! se rechaza borrar una ruta amplia: $INSTALL_HOME" >&2
        exit 1
        ;;
esac

es_generado() {
    local ruta="$1"
    local marca="$2"
    [[ -f "$ruta" ]] && IFS= read -r primera <"$ruta" && [[ "$primera" == "$marca"* ]]
}

if es_generado "$UNIT_PATH" "# Generated by ParlAR setup.sh."; then
    if command -v systemctl >/dev/null 2>&1; then
        systemctl --user disable --now parlar >/dev/null 2>&1 || true
    fi
    rm -f -- "$UNIT_PATH"
fi

if es_generado "$DESKTOP_PATH" "# Generated by ParlAR install.sh."; then
    rm -f -- "$DESKTOP_PATH"
fi

for comando in parlar parlarctl; do
    destino="$BIN_DIR/$comando"
    esperado="$VENV_DIR/bin/$comando"
    if [[ -L "$destino" && "$(readlink -- "$destino")" == "$esperado" ]]; then
        rm -f -- "$destino"
    fi
done

if [[ -e "$INSTALL_HOME" || -L "$INSTALL_HOME" ]]; then
    rm -rf -- "$INSTALL_HOME"
fi

if command -v systemctl >/dev/null 2>&1; then
    systemctl --user daemon-reload >/dev/null 2>&1 || true
fi

echo "==> ParlAR desinstalado. Configuración y transcripts fueron preservados."
