#!/usr/bin/env bash
# Desinstala artefactos generados por install.sh; conserva config y datos.
set -euo pipefail

DATA_BASE="${XDG_DATA_HOME:-$HOME/.local/share}"
CONFIG_BASE="${XDG_CONFIG_HOME:-$HOME/.config}"
INSTALL_HOME_ORIGINAL="${PARLAR_INSTALL_HOME:-$DATA_BASE/parlar}"
INSTALL_HOME="$INSTALL_HOME_ORIGINAL"
BIN_DIR="${PARLAR_BIN_DIR:-$HOME/.local/bin}"
DESKTOP_PATH="$DATA_BASE/applications/parlar.desktop"
UNIT_PATH="$CONFIG_BASE/systemd/user/parlar.service"
AUTOSTART_PATH="$CONFIG_BASE/autostart/parlar-systemd.desktop"
LEGACY_ENABLE_PATH="$CONFIG_BASE/systemd/user/default.target.wants/parlar.service"

uso() {
    cat <<'EOF'
Uso: ./uninstall.sh

Desinstala ParlAR de la cuenta de usuario.
Conserva la configuración y los transcripts.

  -h, --help    muestra esta ayuda sin modificar el sistema
EOF
}

while (($#)); do
    case "$1" in
        -h|--help)
            uso
            exit 0
            ;;
        *)
            echo "!! opción desconocida: $1" >&2
            uso >&2
            exit 2
            ;;
    esac
done

# ``test -L ruta/`` sigue el enlace por el separador final. Colapsamos solo
# separadores finales, preservando la identidad léxica de la raíz que se va a
# comprobar y usar. Los componentes . y .. se rechazan: normalizarlos podría
# cambiar qué enlace se inspecciona respecto del path que luego recibe rm.
while [[ "$INSTALL_HOME" != "/" && "$INSTALL_HOME" == */ ]]; do
    INSTALL_HOME="${INSTALL_HOME%/}"
done
case "$INSTALL_HOME" in
    */./*|*/.|*/../*|*/..)
        echo "!! ruta de instalación insegura: $INSTALL_HOME_ORIGINAL" >&2
        exit 1
        ;;
esac

if [[ "$INSTALL_HOME" != /* \
        || "$(basename -- "$INSTALL_HOME")" != "parlar" \
        || "$(dirname -- "$INSTALL_HOME")" == "/" ]]; then
    echo "!! ruta de instalación insegura: $INSTALL_HOME_ORIGINAL" >&2
    exit 1
fi
case "$INSTALL_HOME" in
    /|"$HOME"|"$HOME"/)
        echo "!! se rechaza borrar una ruta amplia: $INSTALL_HOME" >&2
        exit 1
        ;;
esac
VENV_DIR="$INSTALL_HOME/venv"

es_generado() {
    local ruta="$1"
    local marca="$2"
    [[ -f "$ruta" ]] && IFS= read -r primera <"$ruta" && [[ "$primera" == "$marca"* ]]
}

es_target_comando_propio() {
    local target="$1"
    local comando="$2"
    local relativo
    [[ "$target" == "$INSTALL_HOME/"* ]] || return 1
    relativo="${target#"$INSTALL_HOME"}"
    while [[ "$relativo" == /* ]]; do
        relativo="${relativo#/}"
    done
    [[ "$relativo" == "venv/bin/$comando" ]]
}

if es_generado "$UNIT_PATH" "# Generated by ParlAR setup.sh."; then
    if command -v systemctl >/dev/null 2>&1; then
        systemctl --user stop parlar.service >/dev/null 2>&1 || true
        systemctl --user disable parlar.service >/dev/null 2>&1 || true
    fi
    if [[ -L "$LEGACY_ENABLE_PATH" ]]; then
        rm -f -- "$LEGACY_ENABLE_PATH"
    fi
    rm -f -- "$UNIT_PATH"
fi

if es_generado "$AUTOSTART_PATH" "# Generated by ParlAR install.sh."; then
    rm -f -- "$AUTOSTART_PATH"
fi

if es_generado "$DESKTOP_PATH" "# Generated by ParlAR install.sh."; then
    rm -f -- "$DESKTOP_PATH"
fi

for comando in parlar parlarctl; do
    destino="$BIN_DIR/$comando"
    if [[ -L "$destino" ]]; then
        target="$(readlink -- "$destino")"
        if es_target_comando_propio "$target" "$comando"; then
            rm -f -- "$destino"
        fi
    fi
done

if [[ -L "$INSTALL_HOME" ]]; then
    echo "!! la raíz de instalación es un enlace simbólico; no se sigue ni elimina: $INSTALL_HOME" >&2
elif [[ -d "$INSTALL_HOME" ]]; then
    if [[ -e "$VENV_DIR" || -L "$VENV_DIR" ]]; then
        rm -rf -- "$VENV_DIR"
    fi
    rmdir -- "$INSTALL_HOME" 2>/dev/null || true
fi

if command -v systemctl >/dev/null 2>&1; then
    systemctl --user daemon-reload >/dev/null 2>&1 || true
fi

echo "==> ParlAR desinstalado. Configuración, transcripts y otros datos fueron preservados."
