"""Contrato XDG del control de autostart, sin login ni display reales."""

import os
import tempfile
import unittest
from pathlib import Path
from unittest import mock

import scripts.render_desktop as render_desktop
from parlar import autostart
from parlar.config import Config


UNIT = """# Generated by ParlAR setup.sh. Local edits may be replaced by a later setup run.
[Unit]
Description=ParlAR
[Service]
ExecStart=/opt/parlar/venv/bin/parlar
"""


class PruebasAutostartXDG(unittest.TestCase):
    def setUp(self):
        self.temporal = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporal.cleanup)
        self.base = Path(self.temporal.name)
        self.home = self.base / "home"
        self.config = self.base / "config"
        self.sistema = self.base / "etc-xdg"
        self.entorno = {
            "XDG_CONFIG_HOME": str(self.config),
            "XDG_CONFIG_DIRS": str(self.sistema),
        }

    @property
    def entrada(self):
        return self.config / "autostart" / autostart.NOMBRE_AUTOSTART

    @property
    def unit(self):
        return self.config / "systemd" / "user" / autostart.NOMBRE_UNIT

    def instalar_unit(self):
        self.unit.parent.mkdir(parents=True, exist_ok=True)
        self.unit.write_text(UNIT, encoding="utf-8")

    def escribir_entrada(self, contenido=autostart.CONTENIDO_AUTOSTART,
                         *, sistema=False):
        ruta = (
            self.sistema / "autostart" / autostart.NOMBRE_AUTOSTART
            if sistema else self.entrada
        )
        ruta.parent.mkdir(parents=True, exist_ok=True)
        ruta.write_text(contenido, encoding="utf-8")
        return ruta

    def consultar(self):
        return autostart.consultar_autostart(
            self.entorno, home=self.home)

    def establecer(self, activar):
        return autostart.establecer_autostart(
            activar, self.entorno, home=self.home)

    def test_xdg_config_home_personalizado_define_paths(self):
        rutas = autostart.resolver_rutas_autostart(
            self.entorno, home=self.home)
        self.assertEqual(rutas.config_home, self.config)
        self.assertEqual(rutas.autostart_usuario, self.entrada)
        self.assertEqual(
            rutas.autostart_sistema,
            (self.sistema / "autostart" / autostart.NOMBRE_AUTOSTART,),
        )

    def test_entrada_activa_y_unit_static_es_enabled(self):
        self.instalar_unit()
        self.escribir_entrada()
        estado = self.consultar()
        self.assertEqual(estado.estado, "enabled")
        self.assertTrue(estado.activado)
        self.assertNotIn("[Install]", self.unit.read_text())

    def test_unit_instalada_sin_entrada_es_disabled(self):
        self.instalar_unit()
        estado = self.consultar()
        self.assertEqual(estado.estado, "disabled")
        self.assertTrue(estado.modificable)

    def test_hidden_true_es_disabled(self):
        self.instalar_unit()
        self.escribir_entrada(
            autostart.CONTENIDO_AUTOSTART.replace(
                "Terminal=false\n", "Terminal=false\nHidden=true\n"))
        self.assertEqual(self.consultar().estado, "disabled")

    def test_override_personal_hidden_anula_entrada_del_sistema(self):
        self.instalar_unit()
        self.escribir_entrada(sistema=True)
        self.escribir_entrada(
            autostart.CONTENIDO_AUTOSTART.replace(
                "Terminal=false\n", "Terminal=false\nHidden=TrUe\n"))
        estado = self.consultar()
        self.assertEqual(estado.estado, "disabled")
        self.assertEqual(estado.ruta_efectiva, self.entrada)

    def test_entrada_de_sistema_se_usa_si_no_hay_override(self):
        ruta = self.escribir_entrada(sistema=True)
        estado = self.consultar()
        self.assertEqual(estado.estado, "enabled")
        self.assertEqual(estado.ruta_efectiva, ruta)

    def test_hidden_personal_puede_enmascarar_integracion_del_sistema(self):
        self.escribir_entrada(sistema=True)
        self.escribir_entrada(
            autostart.CONTENIDO_AUTOSTART.replace(
                "Terminal=false\n", "Terminal=false\nHidden=true\n"))
        estado = self.consultar()
        self.assertEqual(estado.estado, "disabled")
        self.assertTrue(estado.modificable)

    def test_integracion_ausente_es_unavailable(self):
        estado = self.consultar()
        self.assertEqual(estado.estado, "unavailable")
        self.assertFalse(estado.modificable)
        self.assertIn("no está disponible", estado.mensaje)

    def test_unit_modificada_es_error_y_no_se_sobrescribe(self):
        self.unit.parent.mkdir(parents=True, exist_ok=True)
        self.unit.write_text(
            "[Service]\nExecStart=programa-relativo\n", encoding="utf-8")
        with self.assertLogs("parlar.autostart", level="ERROR"):
            estado = self.consultar()
        self.assertEqual(estado.estado, "error")
        self.assertFalse(estado.modificable)

    def test_error_de_lectura_es_estado_error_sin_path_humano(self):
        self.instalar_unit()
        with (
            self.assertLogs("parlar.autostart", level="ERROR"),
            mock.patch.object(
                Path, "read_text", side_effect=PermissionError("secreto")),
        ):
            estado = self.consultar()
        self.assertEqual(estado.estado, "error")
        self.assertNotIn(str(self.home), estado.mensaje)

    def test_activar_disabled_crea_contenido_del_instalador(self):
        self.instalar_unit()
        resultado = self.establecer(True)
        self.assertEqual(resultado.resultado, "changed")
        self.assertEqual(resultado.estado.estado, "enabled")
        self.assertEqual(
            self.entrada.read_text(encoding="utf-8"),
            render_desktop.renderizar_autostart(),
        )
        self.assertEqual(self.entrada.stat().st_mode & 0o777, 0o644)

    def test_activar_enabled_es_idempotente(self):
        self.instalar_unit()
        self.escribir_entrada()
        with mock.patch.object(autostart, "_escribir_atomico") as escribir:
            resultado = self.establecer(True)
        self.assertEqual(resultado.resultado, "already_enabled")
        escribir.assert_not_called()

    def test_desactivar_enabled_publica_mascara_hidden(self):
        self.instalar_unit()
        self.escribir_entrada()
        resultado = self.establecer(False)
        self.assertEqual(resultado.resultado, "changed")
        self.assertEqual(resultado.estado.estado, "disabled")
        self.assertIn("Hidden=true", self.entrada.read_text())
        self.assertIn(autostart.MARCA_AUTOSTART, self.entrada.read_text())

    def test_desactivar_disabled_es_idempotente(self):
        self.instalar_unit()
        with mock.patch.object(autostart, "_escribir_atomico") as escribir:
            resultado = self.establecer(False)
        self.assertEqual(resultado.resultado, "already_disabled")
        escribir.assert_not_called()

    def test_publicacion_es_atomica(self):
        self.instalar_unit()
        replace_real = os.replace
        destinos = []

        def observar(origen, destino):
            destinos.append((Path(origen), Path(destino)))
            replace_real(origen, destino)

        with mock.patch.object(
                autostart.os, "replace", side_effect=observar):
            resultado = self.establecer(True)
        self.assertEqual(resultado.resultado, "changed")
        self.assertEqual(destinos[0][1], self.entrada)
        self.assertNotEqual(destinos[0][0], self.entrada)

    def test_fallo_de_escritura_refresca_y_no_miente(self):
        self.instalar_unit()
        self.escribir_entrada()
        with (
            self.assertLogs("parlar.autostart", level="ERROR"),
            mock.patch.object(
                autostart, "_escribir_atomico",
                side_effect=OSError("solo lectura")),
        ):
            resultado = self.establecer(False)
        self.assertEqual(resultado.resultado, "failed")
        self.assertEqual(resultado.estado.estado, "enabled")
        self.assertNotIn("Hidden=true", self.entrada.read_text())

    def test_no_reemplaza_entrada_personal_ajena(self):
        self.instalar_unit()
        ajena = "[Desktop Entry]\nType=Application\nExec=otra-app\n"
        self.escribir_entrada(ajena)
        resultado = self.establecer(True)
        self.assertEqual(resultado.resultado, "failed")
        self.assertEqual(self.entrada.read_text(), ajena)

    def test_cambiar_autostart_no_importa_launcher_app_ni_subprocess(self):
        self.instalar_unit()
        with (
            mock.patch("subprocess.Popen") as popen,
            mock.patch.object(Config, "save") as guardar_config,
        ):
            resultado = self.establecer(True)
        self.assertEqual(resultado.resultado, "changed")
        popen.assert_not_called()
        guardar_config.assert_not_called()

    def test_reinstall_restaura_entrada_oculta_con_contrato_canonico(self):
        self.instalar_unit()
        self.escribir_entrada()
        self.assertEqual(self.establecer(False).resultado, "changed")
        self.assertEqual(
            render_desktop.instalar(
                render_desktop.renderizar_autostart(), self.entrada),
            "instalado",
        )
        self.assertEqual(self.consultar().estado, "enabled")

    def test_xdg_config_home_relativo_se_ignora(self):
        rutas = autostart.resolver_rutas_autostart(
            {"XDG_CONFIG_HOME": "relativo"}, home=self.home)
        self.assertEqual(rutas.config_home, self.home / ".config")


if __name__ == "__main__":
    unittest.main()
