"""Estado y modificación segura del autostart XDG de ParlAR.

El servicio de usuario es deliberadamente static. El inicio de sesión lo
decide la entrada ``parlar-systemd.desktop`` según la precedencia XDG, sin
consultar ni modificar el estado ``enabled`` de systemd.
"""

from __future__ import annotations

import logging
import os
import stat
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Literal, Mapping


NOMBRE_AUTOSTART = "parlar-systemd.desktop"
NOMBRE_UNIT = "parlar.service"
MARCA_AUTOSTART = "# Generated by ParlAR install.sh."
MARCA_UNIT = "# Generated by ParlAR setup.sh."
EXEC_AUTOSTART = "systemctl --user start parlar.service"

CONTENIDO_AUTOSTART = f"""{MARCA_AUTOSTART} Local edits may be replaced by a later install.
[Desktop Entry]
Type=Application
Name=ParlAR service
Comment=Inicia el servicio local de dictado ParlAR
Exec={EXEC_AUTOSTART}
Terminal=false
X-GNOME-Autostart-enabled=true
StartupNotify=false
"""

_LOG = logging.getLogger(__name__)


@dataclass(frozen=True, slots=True)
class RutasAutostart:
    config_home: Path
    autostart_usuario: Path
    unit_usuario: Path
    autostart_sistema: tuple[Path, ...]


@dataclass(frozen=True, slots=True)
class EstadoAutostart:
    estado: Literal["enabled", "disabled", "unavailable", "error"]
    mensaje: str
    modificable: bool
    ruta_efectiva: Path | None = None

    @property
    def activado(self) -> bool:
        return self.estado == "enabled"


@dataclass(frozen=True, slots=True)
class ResultadoAutostart:
    resultado: Literal[
        "changed", "already_enabled", "already_disabled", "failed"
    ]
    estado: EstadoAutostart
    mensaje: str


def _base_absoluta(valor: str | None, predeterminada: Path) -> Path:
    if valor:
        candidata = Path(valor)
        if candidata.is_absolute():
            return candidata
    return predeterminada


def resolver_rutas_autostart(
        entorno: Mapping[str, str] | None = None,
        *, home: Path | None = None) -> RutasAutostart:
    """Resuelve rutas XDG sin crear directorios ni leer el filesystem."""
    env = os.environ if entorno is None else entorno
    base_home = Path.home() if home is None else Path(home)
    config_home = _base_absoluta(
        env.get("XDG_CONFIG_HOME"), base_home / ".config")
    valor_dirs = env.get("XDG_CONFIG_DIRS") or "/etc/xdg"
    config_dirs = tuple(
        Path(item) for item in valor_dirs.split(":")
        if item and Path(item).is_absolute()
    )
    return RutasAutostart(
        config_home=config_home,
        autostart_usuario=(
            config_home / "autostart" / NOMBRE_AUTOSTART),
        unit_usuario=(
            config_home / "systemd" / "user" / NOMBRE_UNIT),
        autostart_sistema=tuple(
            base / "autostart" / NOMBRE_AUTOSTART
            for base in config_dirs
        ),
    )


def _leer_regular(ruta: Path) -> str | None:
    try:
        info = ruta.lstat()
    except FileNotFoundError:
        return None
    if not stat.S_ISREG(info.st_mode):
        raise OSError(f"la ruta no es un archivo regular: {ruta}")
    return ruta.read_text(encoding="utf-8")


def _valor_desktop(contenido: str, clave: str) -> str | None:
    en_desktop = False
    encontrado = None
    for linea in contenido.splitlines():
        limpia = linea.strip()
        if limpia.startswith("[") and limpia.endswith("]"):
            en_desktop = limpia.casefold() == "[desktop entry]"
            continue
        if not en_desktop or not limpia or limpia.startswith("#"):
            continue
        nombre, separador, valor = limpia.partition("=")
        if separador and nombre.strip().casefold() == clave.casefold():
            encontrado = valor.strip()
    return encontrado


def _es_oculta(contenido: str) -> bool:
    valor = _valor_desktop(contenido, "Hidden")
    return valor is not None and valor.casefold() == "true"


def _entrada_valida(contenido: str) -> bool:
    return (
        contenido.startswith(MARCA_AUTOSTART)
        and _valor_desktop(contenido, "Type") == "Application"
        and _valor_desktop(contenido, "Exec") == EXEC_AUTOSTART
    )


def _unit_instalada(ruta: Path) -> bool:
    contenido = _leer_regular(ruta)
    if contenido is None:
        return False
    valida = (
        contenido.startswith(MARCA_UNIT)
        and any(
            linea.startswith("ExecStart=")
            and linea.removeprefix("ExecStart=").lstrip(':"').startswith("/")
            for linea in contenido.splitlines()
        )
        and "[Install]" not in contenido
    )
    if not valida:
        raise ValueError("la unit instalada de ParlAR no es válida")
    return True


def _estado_error(mensaje: str) -> EstadoAutostart:
    return EstadoAutostart("error", mensaje, False)


def consultar_autostart(
        entorno: Mapping[str, str] | None = None,
        *, home: Path | None = None) -> EstadoAutostart:
    """Obtiene el estado efectivo según precedencia y ``Hidden`` de XDG."""
    rutas = resolver_rutas_autostart(entorno, home=home)
    try:
        unit_instalada = _unit_instalada(rutas.unit_usuario)
        entradas: list[tuple[Path, str]] = []
        for ruta in (
                rutas.autostart_usuario, *rutas.autostart_sistema):
            contenido = _leer_regular(ruta)
            if contenido is not None:
                entradas.append((ruta, contenido))

        gestionadas = [
            (ruta, contenido) for ruta, contenido in entradas
            if contenido.startswith(MARCA_AUTOSTART)
        ]
        sistema_gestionado = any(
            ruta in rutas.autostart_sistema
            for ruta, _contenido in gestionadas
        )
        if not unit_instalada and not sistema_gestionado:
            return EstadoAutostart(
                "unavailable",
                "El inicio automático no está disponible en esta instalación.",
                False,
            )

        if not entradas:
            return EstadoAutostart(
                "disabled", "El inicio automático está desactivado.", True)

        ruta, contenido = entradas[0]
        if ruta == rutas.autostart_usuario and not contenido.startswith(
                MARCA_AUTOSTART):
            return _estado_error(
                "No se puede administrar el inicio automático porque existe "
                "una configuración personal no gestionada por ParlAR.")
        if not _entrada_valida(contenido):
            return _estado_error(
                "La integración de inicio automático de ParlAR no es válida.")
        if _es_oculta(contenido):
            return EstadoAutostart(
                "disabled", "El inicio automático está desactivado.", True, ruta)
        return EstadoAutostart(
            "enabled",
            "ParlAR se iniciará en segundo plano cuando abras tu sesión.",
            True,
            ruta,
        )
    except (OSError, UnicodeError, ValueError):
        _LOG.exception("no se pudo consultar autostart en %s", rutas.config_home)
        return _estado_error(
            "No se pudo comprobar el inicio automático de ParlAR.")


def _contenido_oculto() -> str:
    return CONTENIDO_AUTOSTART.replace(
        "Terminal=false\n", "Terminal=false\nHidden=true\n")


def _escribir_atomico(contenido: str, destino: Path) -> None:
    destino.parent.mkdir(parents=True, exist_ok=True)
    descriptor, nombre_temporal = tempfile.mkstemp(
        prefix=f".{destino.name}.tmp-", dir=destino.parent)
    temporal = Path(nombre_temporal)
    pendiente = True
    try:
        os.fchmod(descriptor, 0o644)
        with os.fdopen(descriptor, "w", encoding="utf-8") as archivo:
            descriptor = None
            archivo.write(contenido)
            archivo.flush()
            os.fsync(archivo.fileno())
        os.replace(temporal, destino)
        pendiente = False
        destino.chmod(0o644)
    finally:
        if descriptor is not None:
            os.close(descriptor)
        if pendiente:
            try:
                temporal.unlink()
            except FileNotFoundError:
                pass


def establecer_autostart(
        activar: bool,
        entorno: Mapping[str, str] | None = None,
        *, home: Path | None = None) -> ResultadoAutostart:
    """Activa o enmascara el autostart personal, sin tocar el runtime."""
    rutas = resolver_rutas_autostart(entorno, home=home)
    anterior = consultar_autostart(entorno, home=home)
    esperado = "enabled" if activar else "disabled"
    if anterior.estado == esperado:
        return ResultadoAutostart(
            f"already_{esperado}", anterior, anterior.mensaje)
    if not anterior.modificable:
        return ResultadoAutostart("failed", anterior, anterior.mensaje)

    try:
        existente = _leer_regular(rutas.autostart_usuario)
        if existente is not None and not existente.startswith(MARCA_AUTOSTART):
            raise PermissionError(
                "la entrada personal no fue generada por ParlAR")
        _escribir_atomico(
            CONTENIDO_AUTOSTART if activar else _contenido_oculto(),
            rutas.autostart_usuario,
        )
    except (OSError, UnicodeError):
        _LOG.exception(
            "no se pudo cambiar autostart en %s", rutas.autostart_usuario)
        real = consultar_autostart(entorno, home=home)
        return ResultadoAutostart(
            "failed",
            real,
            "No se pudo cambiar el inicio automático. "
            "Revisá los permisos de tu configuración de usuario.",
        )

    actual = consultar_autostart(entorno, home=home)
    if actual.estado != esperado:
        _LOG.error(
            "autostart no alcanzó el estado esperado %s: %s",
            esperado,
            actual.estado,
        )
        return ResultadoAutostart(
            "failed", actual,
            "No se pudo confirmar el nuevo estado del inicio automático.")
    return ResultadoAutostart("changed", actual, actual.mensaje)
