#!/usr/bin/env python3
"""Renderiza la unit systemd de usuario con rutas del checkout actual."""

import argparse
import os
import re
from pathlib import Path

MARCA = "# Generated by ParlAR setup.sh."
_CARACTERES_PATH_NO_SOPORTADOS = frozenset({"'", '"', "\\"})
_PLACEHOLDER = re.compile(r"@PARLAR_[A-Z0-9_]+@")
_PLACEHOLDERS_REQUERIDOS = frozenset({
    "@PARLAR_WORKDIR@",
    "@PARLAR_EXECUTABLE@",
})


def _validar_ruta_systemd(valor: Path) -> str:
    texto = str(valor)
    if any(ord(caracter) < 32 or ord(caracter) == 127 for caracter in texto):
        raise ValueError("la ruta contiene caracteres de control")
    if not valor.is_absolute():
        raise ValueError("la ruta de systemd debe ser absoluta")
    for caracter in texto:
        if caracter in _CARACTERES_PATH_NO_SOPORTADOS:
            raise ValueError(
                "la ruta contiene un carácter no soportado por la unit "
                f"systemd: {caracter!r}"
            )
    return texto


def _ruta_working_directory(valor: Path) -> str:
    """Escapa un path, sin aplicar la gramática de comandos Exec*."""
    texto = _validar_ruta_systemd(valor)
    return (texto.replace("\\", "\\\\")
            .replace("%", "%%")
            .replace(" ", "\\x20")
            .replace('"', "\\x22"))


def _argumento_execstart(valor: Path) -> str:
    """Produce un ejecutable literal según systemd.service(5).

    El prefijo ``:`` desactiva expansión de variables para que ``$`` sea parte
    del path; no es un shell ni altera argv.
    """
    texto = _validar_ruta_systemd(valor)
    texto = (texto.replace("\\", "\\\\")
             .replace('"', '\\"')
             .replace("%", "%%"))
    return f':"{texto}"'


def _renderizar_plantilla(
    plantilla: str,
    workdir: Path,
    executable: Path,
) -> str:
    """Inserta valores ya escapados sin reinterpretar su contenido."""
    encontrados = set(_PLACEHOLDER.findall(plantilla))
    desconocidos = encontrados - _PLACEHOLDERS_REQUERIDOS
    if desconocidos:
        detalle = ", ".join(sorted(desconocidos))
        raise ValueError(f"placeholder desconocido en la plantilla: {detalle}")
    faltantes = _PLACEHOLDERS_REQUERIDOS - encontrados
    if faltantes:
        detalle = ", ".join(sorted(faltantes))
        raise ValueError(f"falta placeholder requerido en la plantilla: {detalle}")

    valores = {
        "@PARLAR_WORKDIR@": _ruta_working_directory(workdir),
        "@PARLAR_EXECUTABLE@": _argumento_execstart(executable),
    }
    return _PLACEHOLDER.sub(lambda match: valores[match.group(0)], plantilla)


def renderizar(repo: Path) -> str:
    repo = repo.resolve()
    executable = repo / ".venv" / "bin" / "parlar"
    return renderizar_instalacion(repo, executable)


def renderizar_instalacion(workdir: Path, executable: Path) -> str:
    workdir = workdir.resolve()
    # El entrypoint suele ser un symlink del venv. systemd debe conservar esa
    # ruta estable, no resolverla al intérprete subyacente.
    executable = executable.absolute()
    plantilla = Path(__file__).with_name("parlar.service.in").read_text(
        encoding="utf-8"
    )
    return _renderizar_plantilla(plantilla, workdir, executable)


def instalar(contenido: str, destino: Path) -> str:
    destino = destino.expanduser()
    if destino.exists():
        anterior = destino.read_text(encoding="utf-8")
        if anterior == contenido:
            destino.chmod(0o600)
            return "sin cambios"
        if not anterior.startswith(MARCA):
            raise RuntimeError(
                f"{destino} ya existe y no fue generado por ParlAR; no se reemplaza"
            )

    destino.parent.mkdir(parents=True, exist_ok=True)
    temporal = None
    descriptor = None
    reservado = False
    try:
        for intento in range(100):
            candidata = destino.with_name(
                f".{destino.name}.tmp-{os.getpid()}-{intento}")
            try:
                descriptor = os.open(
                    candidata, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600
                )
            except FileExistsError:
                continue
            temporal = candidata
            reservado = True
            break
        else:
            raise OSError("no se pudo reservar un archivo temporal para la unit")

        archivo = os.fdopen(descriptor, "w", encoding="utf-8")
        descriptor = None
        with archivo:
            archivo.write(contenido)
            archivo.flush()
        os.replace(temporal, destino)
        reservado = False
        temporal = None
    finally:
        if descriptor is not None:
            os.close(descriptor)
        if reservado and temporal is not None:
            try:
                temporal.unlink()
            except FileNotFoundError:
                pass
    destino.chmod(0o600)
    return "instalada"


def main() -> None:
    parser = argparse.ArgumentParser()
    origen = parser.add_mutually_exclusive_group(required=True)
    origen.add_argument("--repo", type=Path)
    origen.add_argument("--workdir", type=Path)
    parser.add_argument("--executable", type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    try:
        if args.repo is not None:
            if args.executable is not None:
                parser.error("--executable solo se usa con --workdir")
            contenido = renderizar(args.repo)
        else:
            if args.executable is None:
                parser.error("--workdir requiere --executable")
            contenido = renderizar_instalacion(
                args.workdir, args.executable)
        estado = instalar(contenido, args.output)
    except (OSError, RuntimeError, ValueError) as exc:
        parser.exit(1, f"!! no se pudo instalar la unit: {exc}\n")
    print(f"==> Unit {estado}: {args.output.expanduser()}")


if __name__ == "__main__":
    main()
