#!/usr/bin/env python3
"""Renderiza la unit systemd de usuario con rutas del checkout actual."""

import argparse
import json
import os
from pathlib import Path

MARCA = "# Generated by ParlAR setup.sh."


def _citar_systemd(valor: Path) -> str:
    texto = str(valor)
    if any(caracter in texto for caracter in ("\0", "\n", "\r")):
        raise ValueError("la ruta contiene caracteres de control")
    texto = texto.replace("%", "%%").replace("$", "$$")
    return json.dumps(texto, ensure_ascii=False)


def renderizar(repo: Path) -> str:
    repo = repo.resolve()
    python = repo / ".venv" / "bin" / "python"
    plantilla = Path(__file__).with_name("parlar.service.in").read_text(
        encoding="utf-8"
    )
    return plantilla.replace(
        "@PARLAR_WORKDIR@", _citar_systemd(repo)
    ).replace(
        "@PARLAR_PYTHON@", _citar_systemd(python)
    )


def instalar(contenido: str, destino: Path) -> str:
    destino = destino.expanduser()
    if destino.exists():
        anterior = destino.read_text(encoding="utf-8")
        if anterior == contenido:
            destino.chmod(0o600)
            return "sin cambios"
        if not anterior.startswith(MARCA):
            raise RuntimeError(
                f"{destino} ya existe y no fue generado por ParlAR; no se reemplaza"
            )

    destino.parent.mkdir(parents=True, exist_ok=True)
    temporal = destino.with_name(f".{destino.name}.tmp-{os.getpid()}")
    descriptor = None
    try:
        descriptor = os.open(
            temporal, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600
        )
        archivo = os.fdopen(descriptor, "w", encoding="utf-8")
        descriptor = None
        with archivo:
            archivo.write(contenido)
            archivo.flush()
        os.replace(temporal, destino)
    finally:
        if descriptor is not None:
            os.close(descriptor)
        try:
            temporal.unlink()
        except FileNotFoundError:
            pass
    destino.chmod(0o600)
    return "instalada"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    try:
        estado = instalar(renderizar(args.repo), args.output)
    except (OSError, RuntimeError, ValueError) as exc:
        parser.exit(1, f"!! no se pudo instalar la unit: {exc}\n")
    print(f"==> Unit {estado}: {args.output.expanduser()}")


if __name__ == "__main__":
    main()
