#!/usr/bin/env python3
"""Renderiza e instala el launcher de usuario sin depender del checkout."""

import argparse
import os
from pathlib import Path

MARCA = "# Generated by ParlAR install.sh."


def _argumento_exec(valor: Path) -> str:
    texto = str(valor.absolute())
    if not valor.is_absolute():
        raise ValueError("el ejecutable del launcher debe ser absoluto")
    if any(ord(caracter) < 32 or ord(caracter) == 127 for caracter in texto):
        raise ValueError("el ejecutable contiene caracteres de control")
    texto = (texto.replace("\\", "\\\\")
             .replace('"', '\\"')
             .replace("`", "\\`")
             .replace("$", "\\$")
             .replace("%", "%%"))
    return f'"{texto}"'


def renderizar(executable: Path) -> str:
    plantilla = Path(__file__).with_name("parlar.desktop.in").read_text(
        encoding="utf-8"
    )
    if plantilla.count("@PARLAR_EXECUTABLE@") != 1:
        raise ValueError("launcher sin placeholder de ejecutable único")
    return plantilla.replace(
        "@PARLAR_EXECUTABLE@", _argumento_exec(executable))


def instalar(contenido: str, destino: Path) -> str:
    destino = destino.expanduser()
    if destino.exists():
        anterior = destino.read_text(encoding="utf-8")
        if anterior == contenido:
            destino.chmod(0o644)
            return "sin cambios"
        if not anterior.startswith(MARCA):
            raise RuntimeError(
                f"{destino} ya existe y no fue generado por ParlAR; "
                "no se reemplaza"
            )

    destino.parent.mkdir(parents=True, exist_ok=True)
    temporal = destino.with_name(f".{destino.name}.tmp-{os.getpid()}")
    descriptor = None
    try:
        descriptor = os.open(
            temporal, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o644)
        archivo = os.fdopen(descriptor, "w", encoding="utf-8")
        descriptor = None
        with archivo:
            archivo.write(contenido)
            archivo.flush()
        os.replace(temporal, destino)
        temporal = None
    finally:
        if descriptor is not None:
            os.close(descriptor)
        if temporal is not None:
            try:
                temporal.unlink()
            except FileNotFoundError:
                pass
    destino.chmod(0o644)
    return "instalado"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--executable", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    try:
        estado = instalar(renderizar(args.executable), args.output)
    except (OSError, RuntimeError, ValueError) as exc:
        parser.exit(1, f"!! no se pudo instalar el launcher: {exc}\n")
    print(f"==> Launcher {estado}: {args.output.expanduser()}")


if __name__ == "__main__":
    main()
