#!/usr/bin/env python3
"""Renderiza la unit systemd de usuario con rutas del checkout actual."""

import argparse
import os
from pathlib import Path

MARCA = "# Generated by ParlAR setup.sh."


def _validar_ruta_systemd(valor: Path) -> str:
    texto = str(valor)
    if any(ord(caracter) < 32 or ord(caracter) == 127 for caracter in texto):
        raise ValueError("la ruta contiene caracteres de control")
    if not valor.is_absolute():
        raise ValueError("la ruta de systemd debe ser absoluta")
    return texto


def _ruta_working_directory(valor: Path) -> str:
    """Escapa un path, sin aplicar la gramática de comandos Exec*."""
    texto = _validar_ruta_systemd(valor)
    return (texto.replace("\\", "\\\\")
            .replace("%", "%%")
            .replace(" ", "\\x20")
            .replace('"', "\\x22"))


def _argumento_execstart(valor: Path) -> str:
    """Produce un ejecutable literal según systemd.service(5).

    El prefijo ``:`` desactiva expansión de variables para que ``$`` sea parte
    del path; no es un shell ni altera argv.
    """
    texto = _validar_ruta_systemd(valor)
    texto = (texto.replace("\\", "\\\\")
             .replace('"', '\\"')
             .replace("%", "%%"))
    return f':"{texto}"'


def renderizar(repo: Path) -> str:
    repo = repo.resolve()
    python = repo / ".venv" / "bin" / "python"
    plantilla = Path(__file__).with_name("parlar.service.in").read_text(
        encoding="utf-8"
    )
    return plantilla.replace(
        "@PARLAR_WORKDIR@", _ruta_working_directory(repo)
    ).replace(
        "@PARLAR_PYTHON@", _argumento_execstart(python)
    )


def instalar(contenido: str, destino: Path) -> str:
    destino = destino.expanduser()
    if destino.exists():
        anterior = destino.read_text(encoding="utf-8")
        if anterior == contenido:
            destino.chmod(0o600)
            return "sin cambios"
        if not anterior.startswith(MARCA):
            raise RuntimeError(
                f"{destino} ya existe y no fue generado por ParlAR; no se reemplaza"
            )

    destino.parent.mkdir(parents=True, exist_ok=True)
    temporal = None
    descriptor = None
    reservado = False
    try:
        for intento in range(100):
            candidata = destino.with_name(
                f".{destino.name}.tmp-{os.getpid()}-{intento}")
            try:
                descriptor = os.open(
                    candidata, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600
                )
            except FileExistsError:
                continue
            temporal = candidata
            reservado = True
            break
        else:
            raise OSError("no se pudo reservar un archivo temporal para la unit")

        archivo = os.fdopen(descriptor, "w", encoding="utf-8")
        descriptor = None
        with archivo:
            archivo.write(contenido)
            archivo.flush()
        os.replace(temporal, destino)
        reservado = False
        temporal = None
    finally:
        if descriptor is not None:
            os.close(descriptor)
        if reservado and temporal is not None:
            try:
                temporal.unlink()
            except FileNotFoundError:
                pass
    destino.chmod(0o600)
    return "instalada"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    try:
        estado = instalar(renderizar(args.repo), args.output)
    except (OSError, RuntimeError, ValueError) as exc:
        parser.exit(1, f"!! no se pudo instalar la unit: {exc}\n")
    print(f"==> Unit {estado}: {args.output.expanduser()}")


if __name__ == "__main__":
    main()
