#!/usr/bin/env python3
"""Renderiza e instala el launcher de usuario sin depender del checkout."""

import argparse
import os
from pathlib import Path

MARCA = "# Generated by ParlAR install.sh."
MARCA_ICONO = "<!-- Generated by ParlAR install.sh."


def _argumento_exec(valor: Path) -> str:
    texto = str(valor.absolute())
    if not valor.is_absolute():
        raise ValueError("el ejecutable del launcher debe ser absoluto")
    if any(ord(caracter) < 32 or ord(caracter) == 127 for caracter in texto):
        raise ValueError("el ejecutable contiene caracteres de control")
    texto = (texto.replace("\\", "\\\\\\\\")
             .replace('"', '\\"')
             .replace("`", "\\`")
             .replace("$", "\\$")
             .replace("%", "%%"))
    return f'"{texto}"'


def renderizar(executable: Path) -> str:
    plantilla = Path(__file__).with_name("parlar.desktop.in").read_text(
        encoding="utf-8"
    )
    if plantilla.count("@PARLAR_EXECUTABLE@") != 1:
        raise ValueError("launcher sin placeholder de ejecutable único")
    return plantilla.replace(
        "@PARLAR_EXECUTABLE@", _argumento_exec(executable))


def cargar_icono(origen: Path) -> str:
    contenido = origen.read_text(encoding="utf-8")
    if not contenido.startswith(MARCA_ICONO):
        raise ValueError("el icono de ParlAR no contiene su marca de ownership")
    if "<svg" not in contenido or "</svg>" not in contenido:
        raise ValueError("el recurso de icono no es un SVG completo")
    return contenido


def renderizar_autostart() -> str:
    """Renderiza el arranque gráfico que delega lifecycle a systemd."""
    plantilla = Path(__file__).with_name(
        "parlar-systemd.desktop.in").read_text(encoding="utf-8")
    if "@PARLAR_" in plantilla:
        raise ValueError("autostart contiene placeholders inesperados")
    if plantilla.count(
            "Exec=systemctl --user start parlar.service") != 1:
        raise ValueError("autostart sin Exec systemd único")
    return plantilla


def instalar(contenido: str, destino: Path, *, marca: str = MARCA) -> str:
    destino = destino.expanduser()
    if destino.exists():
        anterior = destino.read_text(encoding="utf-8")
        if anterior == contenido:
            destino.chmod(0o644)
            return "sin cambios"
        if not anterior.startswith(marca):
            raise RuntimeError(
                f"{destino} ya existe y no fue generado por ParlAR; "
                "no se reemplaza"
            )

    destino.parent.mkdir(parents=True, exist_ok=True)
    temporal = destino.with_name(f".{destino.name}.tmp-{os.getpid()}")
    descriptor = None
    try:
        descriptor = os.open(
            temporal, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o644)
        archivo = os.fdopen(descriptor, "w", encoding="utf-8")
        descriptor = None
        with archivo:
            archivo.write(contenido)
            archivo.flush()
        os.replace(temporal, destino)
        temporal = None
    finally:
        if descriptor is not None:
            os.close(descriptor)
        if temporal is not None:
            try:
                temporal.unlink()
            except FileNotFoundError:
                pass
    destino.chmod(0o644)
    return "instalado"


def instalar_icono(contenido: str, destino: Path) -> str:
    destino = destino.expanduser()
    if destino.exists():
        anterior = destino.read_text(encoding="utf-8")
        if anterior == contenido:
            destino.chmod(0o644)
            return "sin cambios"
        if not anterior.startswith(MARCA_ICONO):
            raise RuntimeError(
                f"{destino} ya existe y no fue generado por ParlAR; "
                "no se reemplaza"
            )
    return instalar(contenido, destino, marca=MARCA_ICONO)


def main() -> None:
    parser = argparse.ArgumentParser()
    origen = parser.add_mutually_exclusive_group(required=True)
    origen.add_argument("--executable", type=Path)
    origen.add_argument("--autostart-service", action="store_true")
    origen.add_argument("--icon-source", type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    try:
        if args.autostart_service:
            contenido = renderizar_autostart()
            estado = instalar(contenido, args.output)
        elif args.icon_source is not None:
            contenido = cargar_icono(args.icon_source)
            estado = instalar_icono(contenido, args.output)
        else:
            contenido = renderizar(args.executable)
            estado = instalar(contenido, args.output)
    except (OSError, RuntimeError, ValueError) as exc:
        parser.exit(1, f"!! no se pudo instalar el launcher: {exc}\n")
    print(f"==> Launcher {estado}: {args.output.expanduser()}")


if __name__ == "__main__":
    main()
